apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# - webapp-loadbalancer.yaml
resources:
- deployment.yaml
images:
- name: public.ecr.aws/j2x1y3l5/skafold
  newTag: 82f796d1625c7c89ec5d82f1056cb16f46a67978
