apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# - webapp-loadbalancer.yaml
resources:
- deployment.yaml
images:
- name: public.ecr.aws/j2x1y3l5/skafold
  newTag: ca6a244b10b546d1b284a6de58539ad83fd259c8
